version: "3"
services:
  server:
    build: .
    depends_on:
      - redis
    ports:
      - 5000
    volumes:
      - ./src:/app/src
    labels:
      - traefik.http.routers.server.rule=Host(`server.docker.localhost`)

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - traefik.enable=false
    sysctls:
      net.core.somaxconn: 511

  reverse-proxy:
    image: traefik:v2.0
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
