version: "3"
services:
  server:
    build: .
    depends_on:
      - redis
    ports:
      - 5000
    volumes:
      - ./src:/app/src

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: 511
