version: '3'
services:
  app:
    build: .
    links:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: "511"
