apiVersion: skaffold/v1
kind: Config
metadata:
  name: potential-well-deployment

profiles:
- name: local
  build:
    artifacts:
    - image: fractalfish/quark
      docker:
        dockerfile: Dockerfile
    local:
      push: false
  deploy:
    kubectl:
      manifests:
      - k8s/*.yaml

- name: remote
  build:
    artifacts:
    - image: fractalfish/quark
      docker:
        dockerfile: Dockerfile
    local:
      push: true
  deploy: {}
