version: 2.1

orbs:
  docker: circleci/docker@0.5.20

jobs:
  build-protoc:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: fractalfish/protoc
          path: docker/
          dockerfile: protoc.Dockerfile
      - docker/push:
          image: fractalfish/protoc

workflows:
  commit:
    jobs:
      - build-protoc
