version: 2.1

parameters:
  trigger:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: node:13

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger Workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
