version: 2.1

orbs:
  docker: circleci/docker@0.5.20

jobs:
  build-proto-comp:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: fractalfish/proto-comp
          path: docker/
          dockerfile: proto-comp.dockerfile
      - docker/push:
          image: fractalfish/proto-comp

workflows:
  commit:
    jobs:
      - build-proto-comp
