version: 2.1

executors:
  skaffold:
    docker:
    - image: fractalfish/skaffold:b69a066a1079b5a48095e7f5d2b4653620baf2bf

orbs:
  docker: circleci/docker@0.5.20

jobs:
  build-protoc:
    executor: docker/docker
    steps:
    - setup_remote_docker
    - checkout
    - docker/check
    - docker/build:
        image: fractalfish/protoc
        dockerfile: docker/protoc.Dockerfile
    - docker/push:
        image: fractalfish/protoc
  build-skaffold:
    executor: docker/docker
    steps:
    - setup_remote_docker
    - checkout
    - docker/check
    - docker/build:
        image: fractalfish/skaffold
        dockerfile: docker/skaffold.Dockerfile
    - docker/push:
        image: fractalfish/skaffold
  deploy:
    executor: skaffold
    steps:
    - setup_remote_docker
    - checkout
    - run:
        command: |
          skaffold build -p push

workflows:
  commit:
    jobs:
    - build-protoc
    - build-skaffold
    - deploy
