version: 2.1

parameters:
  # Main workflow: determine what packages to build
  trigger:
    type: boolean
    default: true
  # Separate workflow parameter per package
  potential-well:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger Workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  potential-well:
    when: << pipeline.parameters.potential-well >>
