apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  labels:
    service: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      service: auth
      micro: service
  template:
    metadata:
      labels:
        service: auth
        micro: service
    spec:
      containers:
      - name: auth
        image: fractalfish/auth
        env:
        - name: MICRO_SERVER_ADDRESS
          value: "0.0.0.0:8080"
        ports:
        - containerPort: 8080
          name: auth-port
