// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hashit/hashit.proto

package go_micro_srv_hashit

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncodeRequest struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodeRequest) Reset()         { *m = EncodeRequest{} }
func (m *EncodeRequest) String() string { return proto.CompactTextString(m) }
func (*EncodeRequest) ProtoMessage()    {}
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6aacac7a276b393, []int{0}
}

func (m *EncodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodeRequest.Unmarshal(m, b)
}
func (m *EncodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodeRequest.Marshal(b, m, deterministic)
}
func (m *EncodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodeRequest.Merge(m, src)
}
func (m *EncodeRequest) XXX_Size() int {
	return xxx_messageInfo_EncodeRequest.Size(m)
}
func (m *EncodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EncodeRequest proto.InternalMessageInfo

func (m *EncodeRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EncodeResponse struct {
	EncodedHash          string   `protobuf:"bytes,1,opt,name=encoded_hash,json=encodedHash,proto3" json:"encoded_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncodeResponse) Reset()         { *m = EncodeResponse{} }
func (m *EncodeResponse) String() string { return proto.CompactTextString(m) }
func (*EncodeResponse) ProtoMessage()    {}
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6aacac7a276b393, []int{1}
}

func (m *EncodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncodeResponse.Unmarshal(m, b)
}
func (m *EncodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncodeResponse.Marshal(b, m, deterministic)
}
func (m *EncodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncodeResponse.Merge(m, src)
}
func (m *EncodeResponse) XXX_Size() int {
	return xxx_messageInfo_EncodeResponse.Size(m)
}
func (m *EncodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EncodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EncodeResponse proto.InternalMessageInfo

func (m *EncodeResponse) GetEncodedHash() string {
	if m != nil {
		return m.EncodedHash
	}
	return ""
}

func init() {
	proto.RegisterType((*EncodeRequest)(nil), "go.micro.srv.hashit.EncodeRequest")
	proto.RegisterType((*EncodeResponse)(nil), "go.micro.srv.hashit.EncodeResponse")
}

func init() { proto.RegisterFile("proto/hashit/hashit.proto", fileDescriptor_d6aacac7a276b393) }

var fileDescriptor_d6aacac7a276b393 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x48, 0x2c, 0xce, 0xc8, 0x2c, 0x81, 0x52, 0x7a, 0x60, 0x31, 0x21, 0xe1, 0xf4,
	0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0x3d, 0x88, 0x94, 0x92, 0x2a,
	0x17, 0xaf, 0x6b, 0x5e, 0x72, 0x7e, 0x4a, 0x6a, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90,
	0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84,
	0xa3, 0x64, 0xcc, 0xc5, 0x07, 0x53, 0x56, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xa4, 0xc8, 0xc5,
	0x93, 0x0a, 0x16, 0x49, 0x89, 0x07, 0x19, 0x05, 0x55, 0xce, 0x0d, 0x15, 0xf3, 0x48, 0x2c, 0xce,
	0x30, 0x8a, 0xe5, 0x62, 0xf3, 0x00, 0xdb, 0x22, 0x14, 0xcc, 0xc5, 0x06, 0xd1, 0x2e, 0xa4, 0xa4,
	0x87, 0xc5, 0x15, 0x7a, 0x28, 0x4e, 0x90, 0x52, 0xc6, 0xab, 0x06, 0x62, 0xbf, 0x12, 0x43, 0x12,
	0x1b, 0xd8, 0x5b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x9c, 0xfb, 0x8d, 0xf3, 0x00,
	0x00, 0x00,
}
